#!/usr/bin/env bash
# Script to install an Nginx webserver
sudo apt-get -y update
sudo apt-get -y install nginx
sudo touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
