#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
# and "Hi" for the 9th iteration

i=0
while [ $i -lt 10 ]
do
        echo "Best School"
	if [ $i = 8 ]
        then
	    echo "Hi"
	fi
	(( i++ ))
done

