#!/usr/bin/env bash
# The script loops from 1 to 10
# It displays "bad luck" for 4th loop iteration
# It displays "good luck" for 8th loop iteration
# It displays "Best School" for the other iterations

i=0
while [ $i -lt 10 ]
do
	if [ $i = 3 ]
	then
		echo "bad luck"
	elif [ $i = 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
